const DATABASE_NAME = "@gameplay-nlw";

const COLLECTION_USERS = `${DATABASE_NAME}:users`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;
const COLLECTION_CATEGORIES = `${DATABASE_NAME}:categories`;

export {
    COLLECTION_USERS,
    COLLECTION_APPOINTMENTS,
    COLLECTION_CATEGORIES
}